# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gaurav Jain
email: gauravcdj.98@gmail.com

#write html inside the double quotes to display in jumbotron
description: "<h3>Hello, World! I am </h3><h1>Everything but looks</h1><h3>I'll implement your vision</h3>and keep you on your toes ;)"



baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gauravjain98.io" # the base hostname & protocol for your site
twitter_username: gaurav_jain98
github_username:  GauravJain98
medium_username:  crazcuber
linkedin_username: gauravjain98
facebook_username: gauravj2011
instagram_username: cuber_dude

# tags: [GauravJain98,web,college,blog,blogger,implement,devOps,Python,Django,AWS,GCP,cloud,AZURE,cuberDude,CuberDude,jekyll,developer,designer,freelancer]

# Build settings
markdown: kramdown
